name: dosbox-jz
version: '0.74-2'
summary: Open Source PC/MS-DOS emulator
description: |
  DOSBox is a DOS-emulator that uses the SDL-library which 
  makes DOSBox very easy to port to different platforms. DOSBox has 
  already been ported to many different platforms, such as Windows, BeOS, 
  Linux, MacOS X...
  
  DOSBox also emulates CPU:286/386 realmode/protected mode, 
  Directory FileSystem/XMS/EMS, Tandy/Hercules/CGA/EGA/VGA/VESA graphics, 
  a SoundBlaster/Gravis Ultra Sound card for excellent sound compatibility 
  with older games...
  
  You can "re-live" the good old days with the help of DOSBox, it 
  can run plenty of the old classics that don't run on your new computer!  
  
  DOSBox is totally free of charge and OpenSource.

grade: stable
confinement: strict
base: core18

plugs:
    gnome-3-28-1804:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-28-1804
    gtk-3-themes:
      interface: content
      target: $SNAP/data-dir/themes
      default-provider: gtk-common-themes
    icon-themes:
      interface: content
      target: $SNAP/data-dir/icons
      default-provider: gtk-common-themes
    sound-themes:
      interface: content
      target: $SNAP/data-dir/sounds
      default-provider: gtk-common-themes

environment:
  XDG_DATA_DIRS: $SNAP/data-dir:$XDG_DATA_DIRS
  GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

apps:
  dosbox:
    command: desktop-launch dosbox
    plugs: [home, pulseaudio, desktop, desktop-legacy, wayland, x11, opengl]

parts:
  dosbox:
    plugin: autotools
    source: https://sourceforge.net/projects/dosbox/files/dosbox/0.74-2/dosbox-0.74-2.tar.gz
    build-packages:
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
    stage-packages:
      - libsdl-net1.2
      - libsdl-sound1.2
      - libasound2
      - libslang2
    organize:
      usr/lib/*/libpulse.so.*: usr/lib/
      usr/lib/*/pulseaudio/libpulsecommon*: usr/lib/
    override-build: |
      for p in $SNAPCRAFT_STAGE/../ubuntu-patches/*.patch
      do
        echo Applying $p
        cat $p | patch -p1 
      done
      snapcraftctl build
      echo Stripping
      strip $SNAPCRAFT_PART_INSTALL/bin/* 2>/dev/null || /bin/true
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"
